/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.swing.ImageIcon;

/**
 *
 * @author hfyh
 */
public class CalculadoraGUI extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraGUI
     */
    
    
    public CalculadoraGUI() {
        initComponents();
        
        
        ImageIcon deleteIcon = new ImageIcon("src/main/java/Icons/borrar.png");
        ImageIcon raizIcon = new ImageIcon("src/main/java/Icons/raiz.png");
        
        btnDelete.setIcon(deleteIcon);
        btnRaiz.setIcon(raizIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        btnMultiplicacion = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnDot = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btnCuadrado = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRaiz = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblOperacion = new javax.swing.JTextField();

        jButton28.setText("x");

        jButton29.setText("x");

        jButton30.setText("x");

        jButton31.setText("x");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setBackground(new java.awt.Color(209, 190, 178));
        setResizable(false);

        btnMultiplicacion.setBackground(new java.awt.Color(204, 204, 204));
        btnMultiplicacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnMultiplicacion.setForeground(new java.awt.Color(51, 51, 51));
        btnMultiplicacion.setText("x");
        btnMultiplicacion.setMaximumSize(new java.awt.Dimension(90, 90));
        btnMultiplicacion.setMinimumSize(new java.awt.Dimension(90, 90));
        btnMultiplicacion.setPreferredSize(new java.awt.Dimension(90, 90));
        btnMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicacionActionPerformed(evt);
            }
        });

        btnSuma.setBackground(new java.awt.Color(204, 204, 204));
        btnSuma.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSuma.setForeground(new java.awt.Color(51, 51, 51));
        btnSuma.setText("+");
        btnSuma.setMaximumSize(new java.awt.Dimension(90, 90));
        btnSuma.setMinimumSize(new java.awt.Dimension(90, 90));
        btnSuma.setPreferredSize(new java.awt.Dimension(90, 90));
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });

        btnResta.setBackground(new java.awt.Color(204, 204, 204));
        btnResta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnResta.setForeground(new java.awt.Color(51, 51, 51));
        btnResta.setText("-");
        btnResta.setMaximumSize(new java.awt.Dimension(90, 90));
        btnResta.setMinimumSize(new java.awt.Dimension(90, 90));
        btnResta.setPreferredSize(new java.awt.Dimension(90, 90));
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });

        btnIgual.setBackground(new java.awt.Color(204, 204, 204));
        btnIgual.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnIgual.setForeground(new java.awt.Color(51, 51, 51));
        btnIgual.setText("=");
        btnIgual.setMaximumSize(new java.awt.Dimension(90, 90));
        btnIgual.setMinimumSize(new java.awt.Dimension(90, 90));
        btnIgual.setPreferredSize(new java.awt.Dimension(90, 90));
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });

        btnDot.setBackground(new java.awt.Color(204, 204, 204));
        btnDot.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDot.setForeground(new java.awt.Color(51, 51, 51));
        btnDot.setText(".");
        btnDot.setMaximumSize(new java.awt.Dimension(90, 90));
        btnDot.setMinimumSize(new java.awt.Dimension(90, 90));
        btnDot.setPreferredSize(new java.awt.Dimension(90, 90));
        btnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDotActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(204, 204, 204));
        btn3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn3.setForeground(new java.awt.Color(51, 51, 51));
        btn3.setText("3");
        btn3.setMaximumSize(new java.awt.Dimension(90, 90));
        btn3.setMinimumSize(new java.awt.Dimension(90, 90));
        btn3.setPreferredSize(new java.awt.Dimension(90, 90));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(204, 204, 204));
        btn9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn9.setForeground(new java.awt.Color(51, 51, 51));
        btn9.setText("9");
        btn9.setMaximumSize(new java.awt.Dimension(90, 90));
        btn9.setMinimumSize(new java.awt.Dimension(90, 90));
        btn9.setPreferredSize(new java.awt.Dimension(90, 90));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(204, 204, 204));
        btn6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn6.setForeground(new java.awt.Color(51, 51, 51));
        btn6.setText("6");
        btn6.setMaximumSize(new java.awt.Dimension(90, 90));
        btn6.setMinimumSize(new java.awt.Dimension(90, 90));
        btn6.setPreferredSize(new java.awt.Dimension(90, 90));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn0.setBackground(new java.awt.Color(204, 204, 204));
        btn0.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn0.setForeground(new java.awt.Color(51, 51, 51));
        btn0.setText("0");
        btn0.setMaximumSize(new java.awt.Dimension(90, 90));
        btn0.setMinimumSize(new java.awt.Dimension(90, 90));
        btn0.setPreferredSize(new java.awt.Dimension(90, 90));
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(204, 204, 204));
        btn2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn2.setForeground(new java.awt.Color(51, 51, 51));
        btn2.setText("2");
        btn2.setMaximumSize(new java.awt.Dimension(90, 90));
        btn2.setMinimumSize(new java.awt.Dimension(90, 90));
        btn2.setPreferredSize(new java.awt.Dimension(90, 90));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(204, 204, 204));
        btn8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn8.setForeground(new java.awt.Color(51, 51, 51));
        btn8.setText("8");
        btn8.setMaximumSize(new java.awt.Dimension(90, 90));
        btn8.setMinimumSize(new java.awt.Dimension(90, 90));
        btn8.setPreferredSize(new java.awt.Dimension(90, 90));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(204, 204, 204));
        btn5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn5.setForeground(new java.awt.Color(51, 51, 51));
        btn5.setText("5");
        btn5.setMaximumSize(new java.awt.Dimension(90, 90));
        btn5.setMinimumSize(new java.awt.Dimension(90, 90));
        btn5.setPreferredSize(new java.awt.Dimension(90, 90));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(204, 204, 204));
        btnClear.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(51, 51, 51));
        btnClear.setText("C");
        btnClear.setMaximumSize(new java.awt.Dimension(90, 90));
        btnClear.setMinimumSize(new java.awt.Dimension(90, 90));
        btnClear.setPreferredSize(new java.awt.Dimension(90, 90));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(204, 204, 204));
        btn1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn1.setForeground(new java.awt.Color(51, 51, 51));
        btn1.setText("1");
        btn1.setMaximumSize(new java.awt.Dimension(90, 90));
        btn1.setMinimumSize(new java.awt.Dimension(90, 90));
        btn1.setPreferredSize(new java.awt.Dimension(90, 90));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(204, 204, 204));
        btn7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn7.setForeground(new java.awt.Color(51, 51, 51));
        btn7.setText("7");
        btn7.setMaximumSize(new java.awt.Dimension(90, 90));
        btn7.setMinimumSize(new java.awt.Dimension(90, 90));
        btn7.setPreferredSize(new java.awt.Dimension(90, 90));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(204, 204, 204));
        btn4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn4.setForeground(new java.awt.Color(51, 51, 51));
        btn4.setText("4");
        btn4.setMaximumSize(new java.awt.Dimension(90, 90));
        btn4.setMinimumSize(new java.awt.Dimension(90, 90));
        btn4.setPreferredSize(new java.awt.Dimension(90, 90));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btnCuadrado.setBackground(new java.awt.Color(204, 204, 204));
        btnCuadrado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCuadrado.setForeground(new java.awt.Color(51, 51, 51));
        btnCuadrado.setText("x²");
        btnCuadrado.setMaximumSize(new java.awt.Dimension(90, 90));
        btnCuadrado.setMinimumSize(new java.awt.Dimension(90, 90));
        btnCuadrado.setPreferredSize(new java.awt.Dimension(90, 90));
        btnCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuadradoActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(204, 204, 204));
        btnDelete.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(51, 51, 51));
        btnDelete.setMaximumSize(new java.awt.Dimension(90, 90));
        btnDelete.setMinimumSize(new java.awt.Dimension(90, 90));
        btnDelete.setPreferredSize(new java.awt.Dimension(90, 90));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnRaiz.setBackground(new java.awt.Color(204, 204, 204));
        btnRaiz.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnRaiz.setForeground(new java.awt.Color(51, 51, 51));
        btnRaiz.setMaximumSize(new java.awt.Dimension(90, 90));
        btnRaiz.setMinimumSize(new java.awt.Dimension(90, 90));
        btnRaiz.setPreferredSize(new java.awt.Dimension(90, 90));
        btnRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaizActionPerformed(evt);
            }
        });

        btnDivision.setBackground(new java.awt.Color(204, 204, 204));
        btnDivision.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDivision.setForeground(new java.awt.Color(51, 51, 51));
        btnDivision.setText("÷");
        btnDivision.setMaximumSize(new java.awt.Dimension(90, 90));
        btnDivision.setMinimumSize(new java.awt.Dimension(90, 90));
        btnDivision.setPreferredSize(new java.awt.Dimension(90, 90));
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Calculadora");

        lblOperacion.setEditable(false);
        lblOperacion.setBackground(new java.awt.Color(153, 153, 153));
        lblOperacion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblOperacion.setForeground(new java.awt.Color(51, 51, 51));
        lblOperacion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnMultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(lblOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRaiz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        btnIgualActionPerformed(evt);
    }//GEN-LAST:event_btn0ActionPerformed
                   
                                  

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        // TODO add your handling code here:
        btnIgualActionPerformed(evt);
    }//GEN-LAST:event_btnDivisionActionPerformed

    private void btnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaizActionPerformed
        // TODO add your handling code here:
        btnIgualActionPerformed(evt);
    }//GEN-LAST:event_btnRaizActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        // TODO add your handling code here:


        if (evt.getSource() == btnIgual) {
            System.out.println("La operacion a realizar; "+lblOperacion.getText());
        }

        if (evt.getSource() == btnClear) {
            lblOperacion.setText("");
        } else if (evt.getSource() == btnDelete){
            String texto = lblOperacion.getText();
            if (texto != null && texto.length() > 0) {
                // Elimina la última letra
                texto = texto.substring(0, texto.length() - 1);
            }
            lblOperacion.setText(texto);
        } else if (evt.getSource() == btn0){
            if (lblOperacion.getText() != "0") {
                lblOperacion.setText(lblOperacion.getText()+"0");
            }
            
        } else if (evt.getSource() == btn1){
            lblOperacion.setText(lblOperacion.getText()+"1");
        } else if (evt.getSource() == btn2){
            lblOperacion.setText(lblOperacion.getText()+"2");
        } else if (evt.getSource() == btn3){
            lblOperacion.setText(lblOperacion.getText()+"3");
        } else if (evt.getSource() == btn4){
            lblOperacion.setText(lblOperacion.getText()+"4");
        } else if (evt.getSource() == btn5){
            lblOperacion.setText(lblOperacion.getText()+"5");
        } else if (evt.getSource() == btn6){
            lblOperacion.setText(lblOperacion.getText()+"6");
        } else if (evt.getSource() == btn7){
            lblOperacion.setText(lblOperacion.getText()+"7");
        } else if (evt.getSource() == btn8){
            lblOperacion.setText(lblOperacion.getText()+"8");
        } else if (evt.getSource() == btn9){
            lblOperacion.setText(lblOperacion.getText()+"9");
        } else if (evt.getSource() == btnDot){
            lblOperacion.setText(lblOperacion.getText()+".");
        } else if (evt.getSource() == btnMultiplicacion){
            lblOperacion.setText(lblOperacion.getText()+" * ");
        } else if (evt.getSource() == btnSuma){
            lblOperacion.setText(lblOperacion.getText()+" + ");
        } else if (evt.getSource() == btnDivision){
            lblOperacion.setText(lblOperacion.getText()+" / ");
        } else if(evt.getSource() == btnCuadrado){
            String numeros = lblOperacion.getText();
            try {
                int numero = Integer.parseInt(numeros);
                Double numeroCuadrado = Math.pow(numero, 2);
                lblOperacion.setText(numero+"² = "+numeroCuadrado);
            } catch (NumberFormatException e) {
                lblOperacion.setText("");
            }

        } else if (evt.getSource() == btnResta) {
            lblOperacion.setText(lblOperacion.getText()+" - ");
        }


    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuadradoActionPerformed
        // TODO add your handling code here:
        btnIgualActionPerformed(evt);
    }//GEN-LAST:event_btnCuadradoActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        btnIgualActionPerformed(evt);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        btnIgualActionPerformed(evt);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        btnIgualActionPerformed(evt);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        btnIgualActionPerformed(evt);
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        btnIgualActionPerformed(evt);
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicacionActionPerformed
        // TODO add your handling code here:
        btnIgualActionPerformed(evt);
    }//GEN-LAST:event_btnMultiplicacionActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        btnIgualActionPerformed(evt);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        btnIgualActionPerformed(evt);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        btnIgualActionPerformed(evt);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        // TODO add your handling code here:
        btnIgualActionPerformed(evt);
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        btnIgualActionPerformed(evt);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        btnIgualActionPerformed(evt);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        btnIgualActionPerformed(evt);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        // TODO add your handling code here:
        btnIgualActionPerformed(evt);
    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDotActionPerformed
        // TODO add your handling code here:
        btnIgualActionPerformed(evt);
    }//GEN-LAST:event_btnDotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCuadrado;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnDot;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMultiplicacion;
    private javax.swing.JButton btnRaiz;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSuma;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField lblOperacion;
    // End of variables declaration//GEN-END:variables
}
